networks:
  default:
    internal: false
    name: ${NETWORK_NAME}

services:
  traefik:
    image: traefik:2.6
    restart: ${RESTART}
    command:
      - "--providers.docker"
      - "--providers.docker.exposedByDefault=false"
      - "--api.dashboard=${DASHBOARD}"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      # Enable ACME (Let's Encrypt): automatic SSL.
      - "--certificatesresolvers.letsencrypt.acme.email=${ACME_EMAIL}"
      - "--certificatesresolvers.letsencrypt.acme.storage=/etc/traefik/acme/acme.json"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
      # Global redirect to https.
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      # Setup dynamic configuration
      - "--providers.file.directory=/etc/traefik/traefik.d"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./letsencrypt/acme.json:/etc/traefik/acme/acme.json
      - ./traefik.d:/etc/traefik/traefik.d
    labels:
      - "traefik.enable=true"
      # http
      - "traefik.http.routers.dashboard-http.entrypoints=web"
      - "traefik.http.routers.dashboard-http.rule=Host(`${HOST}`)"
      - "traefik.http.routers.dashboard-http.service=api@internal"
      # https
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.dashboard.rule=Host(`${HOST}`)"
      - "traefik.http.routers.dashboard.tls=true"
      - "traefik.http.routers.dashboard.tls.certresolver=letsencrypt"
      - "traefik.http.routers.dashboard.service=api@internal"
