# Traefik dynamic configuration file
# See https://doc.traefik.io/traefik/getting-started/configuration-overview/#the-dynamic-configuration

http:
  middlewares:
    redirect-to-non-www:
      redirectRegex:
        regex: "^https://www.(.*)"
        replacement: "https://$${1}"
        permanent: true